services:
  app:
    build:
      context: .
    command: >
      wait-for-it db:5432 
      -- bash -c 
        'python -m manage migrate && python -m manage runserver 0.0.0.0:8000'
    env_file:
      - ./.env.dev
    volumes:
      - .:/django
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=saitama
      - POSTGRES_DB=anime_list
      - POSTGRES_PASSWORD=onepunch